name: Publish to PowerShell Gallery
on: 
  workflow_dispatch:
    inputs:
      path:
        description: 'The path of the module to publish'
        required: true
        type: string

jobs:
    build:
      name: Build
      runs-on: [windows-latest]
      steps:
        - uses: actions/checkout@v3
        - name: Publish
          run: .\publishPsGallery.ps1
          shell: pwsh
          env: 
            apitoken: ${{ secrets.GALLERY_API_KEY }}
            inputpath: ${{ inputs.path }}